import { NextPage } from "next";
import React from "react";
import Head from "next/head";
import Nav from "../component/nav";

const History:NextPage = ()=>{
    return(
        <div>
            <Head>
                <title>経歴</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav
            lang="en"
            root="history"
            />
            <h1
            style={{
                textAlign:"center"
            }}
            >Maiking</h1>
        </div>
    );
}

export default History;