import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../../styles/Home.module.css'
import Nav from '../../component/nav'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yuuki Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav
      lang='en'
      root=''
      />
      <main className={styles.main}>
        MAKING
      </main>
    </div>
  )
}

export default Home
