import { NextPage } from "next";
import  Head  from "next/head";
import  Image  from "next/image";
import { useEffect, useState } from "react";
import Nav from "../component/nav";
import styles from '../styles/Work.module.css'

type workType = {
    title:string,
    url:string,
    backgroundimg:string,
    usageimg:string,
    sentence:string,
}

const Work: NextPage = () => {
    const [works,setWorks] = useState<workType[]>([]);
    const [titles,setTitles] = useState<string[]>([]);
    useEffect(()=>{
        let newworks = [
            {
                title:"ポートフォリオサイト",
                url:"localhost",
                usageimg:"",
                backgroundimg:"",
                sentence:"<h1>どんなサイト？</h1><p>このサイトのこと</p>"
            },
            {
                title:"最適グラボ",
                url:"https://scf.yukiserv.com",
                usageimg:"https://drive.google.com/uc?export=view&id=18RLTU38ztJiQB8hIs6z6HjKSZ5bAMb7P",
                backgroundimg:"/scf.png",
                sentence:"<h1>どんなサイト?</h1><p>アプリ名からグラボを検索するサイトです。</p>"
            }
        ];
        setWorks(newworks);

        let newtitles = [];
        for(let i = 0;i<newworks.length;i++){
            newtitles.push(newworks[i].title);
        }
        setTitles(newtitles);

    },[]);

    return(
        <div>
            <Head>
                <title>作品</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.top}>
            <Nav
            root="work"
            />
                <div className={styles.head1}>
                    <h1>作 品</h1>
                </div>
                <div className={styles.index}>
                    <h2>目 次</h2>
                    <ul>
                        {titles.map((item,key)=>{
                            return(<li key={key}><a href={"#"+key}>{item}</a></li>);
                        })}
                    </ul>
                </div>
            </div>
            {/* 内容は背景が関連画像のぼかし、右半分が利用gif、左半分がマークダウン説明文 */}
            {works.map((item,key)=>{
                return(
                    <div 
                    key={key}
                    style={{
                        background:"url("+item.backgroundimg+")",
                        backgroundSize:'cover',
                        position:'relative',
                        height:'100vh',
                        zIndex:0,
                        overflow:"hidden",
                    }}
                    id={key+""}
                    className={styles.imgback}
                    >
                        <div className={styles.prodtitle}>
                            <h2>{item.title}</h2>
                            <a href={item.url}>{item.url}</a>
                        </div>
                        <div className={styles.prod}>
                            <div
                            className={styles.prodleft}
                            >
                                <img src={item.usageimg} alt="使い方" />
                            </div>
                            <div
                            className={styles.prodright}
                            >
                                <div
                                dangerouslySetInnerHTML={{
                                    __html:item.sentence,
                                }}
                                style={{
                                    marginLeft:"3%"
                                }}
                                className={styles.content}
                                />
                            </div>
                        </div>
                    </div>
                );
            })}
        </div>
    );
}

export default Work;